Student_Incident_Tracking_System/ed4all/urls.py
from django.conf.urls import url
from django.contrib import admin
from ed4all import views

urlpatterns = [
    url(r'^$', views.home, name="home"),

    # =========== student login ===========
    url(r'^student_home', views.student_home, name='student_home'),
    url(r'^student_view_detail', views.student_view_detail, name='student_view_detail'),
    url(r'^student_view_incident', views.student_view_incident, name='student_view_incident'),

    # =========== educator login ===========
    url(r'^educator_home', views.educator_home, name='educator_home'),
    url(r'^educator_create_incident', views.educator_create_incident, name='educator_create_incident'),
    url(r'^educator_student_list', views.educator_student_list, name='educator_student_list'),
    url(r'^educator_incident_list', views.educator_incident_list, name='educator_incident_list'),
    url(r'^educator_student_view/(?P<pk>[\w-]+)$', views.educator_student_view, name='educator_student_view'),

    # =========== counselor login ===========
    url(r'^counselor_home', views.counselor_home, name='counselor_home'),
    url(r'^student_list', views.student_list, name='student_list'),
    url(r'^student_view/(?P<pk>[\w-]+)$', views.student_view, name='student_view'),
    url(r'^incident_form', views.incident_create, name='incident_create'),
    url(r'^incident_list', views.incident_list, name='incident_list'),
    url(r'^incident_view/(?P<pk>[\w-]+)/$', views.incident_view, name='incident_view'),
    url(r'^incident_edit/(?P<pk>[\w-]+)/$', views.incident_edit, name='incident_edit'),
    url(r'^incident_delete/(?P<pk>[\w-]+)$', views.incident_delete, name='incident_delete'),

]

Student_Incident_Tracking_System/education4/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^ed4all/', include('ed4all.urls', namespace='ed4all')),

]

Student_Incident_Tracking_System/ed4all/views.py
from ed4all.models import Appointment, Counselor, Educator, Incident, Student, Studentprofile
from django.core.urlresolvers import reverse_lazy, reverse
from django.template import loader
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.forms import ModelForm
from django.views.decorators.csrf import csrf_exempt
from django import forms
from django.core.mail import send_mail


# ========== home =========

def home(request, template_name='ed4all/home.html'):
    incidents = Incident.objects.all()
    contents = {}
    contents["incidents"] = incidents
    return render(request, template_name, contents)


# ========== form =========

class IncidentForm(ModelForm):
    class Meta:
        model = Incident
        fields = ['incidentid', 'studentid', 'incidenttype', 'location', 'educatorid', 'counselorid', 'status']

class IncidentEditForm(ModelForm):
    class Meta:
        model = Incident
        fields = [ 'studentid', 'incidenttype', 'location', 'educatorid', 'counselorid', 'status']

class StudentForm(ModelForm):
    class Meta:
        model = Student
        fields = ['studentid', 'studentlname', 'studentfname', 'studentemailaddress', 'studentage', 'studentdob',
                  'street', 'city', 'zip', 'program', 'trackrepid', 'studentpassword', 'studenttype']


# =========== student login home ==========
@csrf_exempt
def student_home(request):
    err = True
    ctx = {}
    ctx["error"] = err
    if 'sid' in request.session:
        sid = request.session['sid']
        ctx["sid"] = sid
        student = Student.objects.get(studentid=sid)
        ctx['student'] = student
        return render(request, "ed4all/student_home.html", ctx)
    else:
        try:
            if request.method == 'POST':
                sid = request.POST['sid']
                pwd = request.POST['spwd']
                student = Student.objects.get(studentid=sid)
                if pwd == student.studentpassword:
                    ctx['sid'] = sid
                    ctx['student'] = student
                    request.session['sid'] = sid
                    request.session['spwd'] = pwd
                    return render(request, "ed4all/student_home.html", ctx)
                else:
                    err = False
                    ctx["error"] = err
                    ctx["message"] = "Wrong Password/Username"
                    return render(request, 'index.html', ctx)
            else:
                err = False
                ctx["error"] = err
                ctx["message"] = "Wrong Password/Username"
                return render(request, 'index.html', ctx)
        except Student.DoesNotExist:
            err = False
            ctx["error"] = err
            ctx["message"] = "Wrong Password/Username"
            return render(request, 'index.html', ctx)

# =========== faculty login home ==========
@csrf_exempt
def educator_home(request):
    err = True
    ctx = {}
    ctx["error"] = err
    if 'eid' in request.session:
        eid = request.session['eid']
        ctx["eid"] = eid
        educator = Educator.objects.get(educatorid=eid)
        ctx['educator'] = educator
        return render(request, "ed4all/educator_home.html", ctx)
    else:
        try:
            if request.method == 'POST':
                eid = request.POST['eid']
                pwd = request.POST['epwd']
                educator = Educator.objects.get(educatorid=eid)
                if pwd == educator.educatorpassword:
                    ctx['eid'] = eid
                    ctx['educator'] = educator
                    request.session['eid'] = eid
                    request.session['epwd'] = pwd
                    return render(request, "ed4all/educator_home.html", ctx)
                else:
                    err = False
                    ctx["error"] = err
                    ctx["message"] = "Wrong Password/Username"
                    return render(request, 'index.html', ctx)
            else:
                err = False
                ctx["error"] = err
                ctx["message"] = "Wrong Password/Username"
                return render(request, 'index.html', ctx)
        except Student.DoesNotExist:
            err = False
            ctx["error"] = err
            ctx["message"] = "Wrong Password/Username"
            return render(request, 'index.html', ctx)


# =========== counselor login home ==========
@csrf_exempt
def counselor_home(request):
    err = True
    ctx = {}
    ctx["error"] = err
    if 'cid' in request.session:
        cid = request.session['cid']
        ctx["cid"] = cid
        counselor = Counselor.objects.get(counselorid=cid)
        ctx['counselor'] = counselor
        return render(request, "ed4all/counselor_home.html", ctx)
    else:
        try:
            if request.method == 'POST':
                cid = request.POST['cid']
                pwd = request.POST['cpwd']
                counselor = Counselor.objects.get(counselorid=cid)
                if pwd == counselor.counselorpassword:
                    ctx['cid'] = cid
                    ctx['counselor'] = counselor
                    request.session['cid'] = cid
                    request.session['cpwd'] = pwd
                    return render(request, "ed4all/counselor_home.html", ctx)
                else:
                    err = False
                    ctx["error"] = err
                    ctx["message"] = "Wrong Password/Username"
                    return render(request, 'index.html', ctx)
            else:
                err = False
                ctx["error"] = err
                ctx["message"] = "Wrong Password/Username"
                return render(request, 'index.html', ctx)
        except Counselor.DoesNotExist:
            err = False
            ctx["error"] = err
            ctx["message"] = "Wrong Password/Username"
            return render(request, 'index.html', ctx)

# ========== Forms =========

#class IncidentForm(ModelForm):
#    class Meta:
#        model = Incident
#        fields = '__all__'

#class StudentForm(ModelForm):
#    class Meta:
#       model = Student
#        fields = '__all__'

class CounselorForm(ModelForm):
    class Meta:
        model = Counselor
        fields = '__all__'

class EducatorCreateForm(ModelForm):
    incidentid = forms.CharField(label='incidentid')
    educatorid = forms.ModelChoiceField(queryset=Educator.objects.all(), label='ID')
    studentid = forms.ModelChoiceField(queryset=Student.objects.all(), required=False, label='Student ID')
    counselorid = forms.ModelChoiceField(queryset=Counselor.objects.all(), required=False,
                                         label='Counselor')
    location = forms.CharField(label='Location')
    incidenttype = forms.CharField(label='Type')

    class Meta:
        model = Incident
        fields = ['incidentid','educatorid', 'studentid', 'counselorid', 'incidenttype', 'location', 'status']
        widgets = {
            'incidenttype': forms.TextInput,
            'location': forms.TextInput
        }

class StudentProfileForm(ModelForm):
        class Meta:
            model = Studentprofile
            fields = '__all__'

# =========== counselor view student profile and crud incident ==========

def student_list(request,template_name='ed4all/student_list.html'):
    student = Student.objects.all()
    ctx = {}
    ctx['student'] = student
    return render(request, template_name, ctx)

def student_view(request, pk, template_name='ed4all/student_view.html'):
    student= get_object_or_404(Student, studentid=pk)
    trackrep = get_object_or_404(Student,studentid=student.trackrepid)
    profile = Studentprofile.objects.filter(studentid=pk)
    ctx = {}
    ctx["student"] = student
    ctx["trackrep"] = trackrep
    ctx["profile"] = profile
    return render(request, template_name, ctx)

def incident_list(request,template_name='ed4all/incident_list.html'):
    ctx={}
    incident= Incident.objects.all()
    ctx['incident']=incident
    return render(request,template_name,ctx)

def incident_view(request, pk, template_name='ed4all/incident_view.html'):
    incident= get_object_or_404(Incident, incidentid=pk)
    student = Student.objects.filter(incident=pk)
    counselor=Counselor.objects.filter(incident=pk)
    ctx = {}
    ctx["i"] = incident
    ctx["s"] = student
    ctx['c']=counselor
    return render(request, template_name, ctx)

def incident_edit(request, pk, template_name='ed4all/incident_edit.html'):
    incident= get_object_or_404(Incident, incidentid=pk)
    form = IncidentEditForm(request.POST or None, instance=incident)
    if form.is_valid():
        form.save()
        return redirect('ed4all:incident_list')
    ctx = {}
    ctx["form"] = form
    ctx["incident"] = incident
    return render(request, template_name, ctx)

def incident_delete(request, pk, template_name='ed4all/incident_delete.html'):
    incident = get_object_or_404(Incident, incidentid=pk)
    if request.method=='POST':
        incident.delete()
        return redirect('ed4all:incident_list')
    ctx = {}
    ctx["incident"] = incident
    return render(request, template_name, ctx)

def incident_create(request, template_name='ed4all/incident_form.html'):
    form = IncidentForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('ed4all:counselor_home')
    ctx = {}
    ctx["form"] = form
    return render(request, template_name, ctx)

# =========== student view own profile ============
def student_view_detail(request, template_name='ed4all/student_view_detail.html'):
    pk = request.session['sid']
    student = get_object_or_404(Student, studentid=pk)
    trackrep = get_object_or_404(Student, studentid=student.trackrepid)
    profile = Studentprofile.objects.filter(studentid=pk)
    ctx = {}
    ctx["student"] = student
    ctx["trackrep"] = trackrep
    ctx["profile"] = profile
    return render(request, template_name, ctx)

Student_Incident_Tracking_System/ed4all/templates/ed4all/educator_home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet" type="text/css">
    <style>
        body {
            font: 400 15px Candara, Calibri, Segoe, 'Segoe UI', Optima, Arial, sans-serif;
            line-height: 1.8;
            color: #000000;
            background-color: #f2f2f2;
        }
        h2 {
            font-size: 24px;
            color: #000000;
            font-weight: 100;
            margin-bottom: 30px;
            font-family: Candara, Calibri, Segoe, 'Segoe UI', Optima, Arial, sans-serif;
        }
        h4 {
            font-size: 19px;
            line-height: 1.375em;
            color: #303030;
            font-weight: 400;
            margin-bottom: 30px;
            font-family: Candara, Calibri, Segoe, 'Segoe UI', Optima, Arial, sans-serif;
        }
        .jumbotron {
            background-color: transparent;
            color: #000;
            padding: 20px 20px;
            font-family: font-family: Candara, Calibri, Segoe, 'Segoe UI', Optima, Arial, sans-serif;
        }
        .container-fluid {
            padding: 8px 50px;
        }
        .container-down {
            padding: 150px 50px;
        }
        .thumbnail img {
            width: 100%;
            height: 100%;
            margin-bottom: 10px;
        }
        .carousel-indicators li {
            border-color: #1E90FF;
        }
        .carousel-indicators li.active {
            background-color: #1E90FF;
        }
        .item h4 {
            font-size: 19px;
            line-height: 1.375em;
            font-weight: 400;
            font-style: italic;
            margin: 70px 0;
        }
        .item span {
            font-style: normal;
        }
        .panel {
            border: 1px solid #000000;
            border-radius:0 !important;
            transition: box-shadow 0.5s;
        }
        .panel:hover {
            box-shadow: 5px 0px 40px rgba(0,0,0, .2);
        }
        .panel-footer .btn:hover {
            border: 1px solid #000000;
            background-color: #fff !important;
            color: #f4511e;
        }
        .panel-footer h3 {
            font-size: 32px;
        }
        .panel-footer h4 {
            color: #aaa;
            font-size: 14px;
        }
        .panel-footer .btn {
            margin: 15px 0;
            background-color: #000000;
            color: #fff;
        }
        .navbar {
            margin-bottom: 0;
            background-color: #000000;
            z-index: 9999;
            border: 0;
            font-size: 16px !important;
            line-height: 1.42857143 !important;
            letter-spacing: 3px;
            border-radius: 20px;
            font-family: font-family: Candara, Calibri, Segoe, 'Segoe UI', Optima, Arial, sans-serif;
        }
        .navbar li a, .navbar .navbar-brand {
            color: #fff !important;
        }
        .navbar-nav li a:hover, .navbar-nav li.active a {
            color: #000000 !important;
            background-color: #fff !important;
        }
        .navbar-default .navbar-toggle {
            border-color: transparent;
            color: #fff !important;
        }
        footer .glyphicon {
            font-size: 20px;
            margin-bottom: 20px;
            color: #000000;
        }
        @keyframes slide {
            0% {
                opacity: 0;
                transform: translateY(70%);
            }
            100% {
                opacity: 1;
                transform: translateY(0%);
            }
        }
        @-webkit-keyframes slide {
            0% {
                opacity: 0;
                -webkit-transform: translateY(70%);
            }
            100% {
                opacity: 1;
                -webkit-transform: translateY(0%);
            }
        }
    </style>
</head>
<body>
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand">EDUCATOR</a>
        </div>
        <ul class="nav navbar-nav">
            <li class="active"><a href="{% url 'ed4all:educator_home' %}">HOME</a></li>
            <li><a href="{% url 'ed4all:educator_incident_list' %}">INCIDENTS</a></li>
            <li><a href="{% url 'ed4all:educator_student_list' %}">STUDENTS</a></li>
            <li><a href="{% url 'index' %}">LOG OUT</a></li>
        </ul>
    </div>
</nav>

<div class="jumbotron text-center">
    <h1>Educator Dashboard</h1>
    <p>Welcome {{educator.educatorfname}} {{educator.educatorlname}}!</p>
</div>
<div class="container text-center">
    <div class="row">
        <div class="col-sm-6">
            <a href="{% url 'ed4all:educator_create_incident' %}">
                <button type="button" class="btn btn-default btn-block">
                    <span class="glyphicon glyphicon-tag" aria-hidden="true"></span>
                    <h2>Report an Incident</h2>
                </button>
            </a>
        </div>
        <div class="col-sm-6">
            <a href="{% url 'ed4all:educator_student_list' %}">
                <button type="button" class="btn btn-default btn-block">
                    <span class="glyphicon glyphicon-file" aria-hidden="true"></span>
                    <h2>View Students</h2>
                </button>
            </a>
        </div>
    </div>
</div>

<footer class="container-down text-center">
</footer>
</body>
</html>

Student_Incident_Tracking_System/ed4all/templates/ed4all/educator_incident_list.html
<!DOCTYPE html>
<head>
    <meta charset="utf-8">
    {% load static %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet" type="text/css">
    <script type="text/javascript" src="{% static 'ed4all/sorttable.js' %}"></script>
    <style>
        body {
            font: 400 15px Candara, Calibri, Segoe, 'Segoe UI', Optima, Arial, sans-serif;
            line-height: 1.8;
            color: #818181;
        }
        h2 {
            font-size: 24px;
            color: #000000;
            font-weight: 100;
            margin-bottom: 30px;
            font-family: Candara, Calibri, Segoe, 'Segoe UI', Optima, Arial, sans-serif;
        }
        h4 {
            font-size: 19px;
            line-height: 1.375em;
            color: #303030;
            font-weight: 400;
            margin-bottom: 30px;
        }
        .jumbotron {
            background-color: transparent;
            color: #000;
            padding: 20px 20px;
            font-family: font-family: Candara, Calibri, Segoe, 'Segoe UI', Optima, Arial, sans-serif;
        }
        .container-fluid {
            padding: 8px 50px;
        }
        .container-down {
            padding: 150px 50px;
        }
        .thumbnail img {
            width: 100%;
            height: 100%;
            margin-bottom: 10px;
        }
        .carousel-indicators li {
            border-color: #1E90FF;
        }
        .carousel-indicators li.active {
            background-color: #1E90FF;
        }
        .item h4 {
            font-size: 19px;
            line-height: 1.375em;
            font-weight: 400;
            font-style: italic;
            margin: 70px 0;
        }
        .item span {
            font-style: normal;
        }
        .panel {
            border: 1px solid #000000;
            border-radius:0 !important;
            transition: box-shadow 0.5s;
        }
        .panel:hover {
            box-shadow: 5px 0px 40px rgba(0,0,0, .2);
        }
        .panel-footer .btn:hover {
            border: 1px solid #000000;
            background-color: #fff !important;
            color: #f4511e;
        }
        .panel-footer h3 {
            font-size: 32px;
        }
        .panel-footer h4 {
            color: #aaa;
            font-size: 14px;
        }
        .panel-footer .btn {
            margin: 15px 0;
            background-color: #000000;
            color: #fff;
        }
         .panel .panel-heading {
            background-color:#eee;
            color:#666666;
            font-weight: bold;
            cursor: default;
        }
        .navbar {
            margin-bottom: 0;
            background-color: #000000;
            z-index: 9999;
            border: 0;
            font-size: 16px !important;
            line-height: 1.42857143 !important;
            letter-spacing: 3px;
            border-radius: 20px;
            font-family: Candara, Calibri, Segoe, 'Segoe UI', Optima, Arial, sans-serif;
        }
        .navbar li a, .navbar .navbar-brand {
            color: #fff !important;
        }
        .navbar-nav li a:hover, .navbar-nav li.active a {
            color: #000000 !important;
            background-color: #fff !important;
        }
        .navbar-default .navbar-toggle {
            border-color: transparent;
            color: #fff !important;
        }
        footer .glyphicon {
            font-size: 20px;
            margin-bottom: 20px;
            color: #000000;
        }
        @keyframes slide {
            0% {
                opacity: 0;
                transform: translateY(70%);
            }
            100% {
                opacity: 1;
                transform: translateY(0%);
            }
        }
        @-webkit-keyframes slide {
            0% {
                opacity: 0;
                -webkit-transform: translateY(70%);
            }
            100% {
                opacity: 1;
                -webkit-transform: translateY(0%);
            }
        }
    </style>
</head>

<body>
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand">EDUCATOR</a>
        </div>
        <ul class="nav navbar-nav">
            <li><a href="{% url 'ed4all:educator_home' %}">HOME</a></li>
            <li class="active"><a href="{% url 'ed4all:educator_incident_list' %}">INCIDENTS</a></li>
            <li><a href="{% url 'ed4all:educator_student_list' %}">STUDENTS</a></li>
            <!--<li><a href="{% url 'ed4all:incident_list' %}">SERVICES</a> </li> -->
            <li><a href="{% url 'index' %}">LOG OUT</a></li>
        </ul>
    </div>
</nav>

<div class="jumbotron text-center">
    <h1>Incidents</h1>
</div>

<div class="panel">
    <div class="container">
         <div class="text-center">
             <table class="table table-bordered table-hover sortable">
            <tbody>
             <thead class="panel-heading">
                <td>Incident ID</td>
                <td>Student ID</td>
                 <td>Counselor ID</td>
                 <td>Incident Type</td>
                 <td>Location</td>
                 <td>Incident Status</td>
                 <td>Update/Delete</td>
            </thead>
             {% for app in incident %}
             <tr>
                <td>{{app.incidentid}}</td>
                <td>{{app.studentid}}</td>
                <td>{{app.counselorid}}</td>
                <td>{{app.incidenttype}}</td>
                 <td>{{app.location}}</td>
                <td>{{app.status}}</td>
                 <td><a href="{% url 'ed4all:incident_edit' app.incidentid %}"
               data-original-title="Edit incident" class="btn btn-info btn-sm" type="button" >
                <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
                Edit</a>
                     <a href="{% url 'ed4all:incident_delete' app.incidentid %}"
               data-original-title="Delete incident" class="btn btn-danger btn-sm" type="button" >
                <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                Delete</a>
                </td>
            </tr>
             {% endfor %}
                 </tbody>
        </table>
         </div>


     </div>
</div>
</body>
</html>

Student_Incident_Tracking_System/ed4all/templates/ed4all/educator_student_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    {% load static %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet" type="text/css">
    <script type="text/javascript" src="{% static 'ed4all/sorttable.js' %}"></script>
    <style>
        body {
            font: 400 15px Candara, Calibri, Segoe, 'Segoe UI', Optima, Arial, sans-serif;
            line-height: 1.8;
            color: #818181;
        }
        h2 {
            font-size: 24px;
            color: #000000;
            font-weight: 100;
            margin-bottom: 30px;
            font-family: Candara, Calibri, Segoe, 'Segoe UI', Optima, Arial, sans-serif;
        }
        h4 {
            font-size: 19px;
            line-height: 1.375em;
            color: #303030;
            font-weight: 400;
            margin-bottom: 30px;
        }
        .jumbotron {
            background-color: transparent;
            color: #000;
            padding: 20px 20px;
            font-family: font-family: Candara, Calibri, Segoe, 'Segoe UI', Optima, Arial, sans-serif;
        }
        .container-fluid {
            padding: 8px 50px;
        }
        .container-down {
            padding: 50px 50px;
        }
        .thumbnail img {
            width: 100%;
            height: 100%;
            margin-bottom: 10px;
        }
        .carousel-indicators li {
            border-color: #1E90FF;
        }
        .carousel-indicators li.active {
            background-color: #1E90FF;
        }
        .item h4 {
            font-size: 19px;
            line-height: 1.375em;
            font-weight: 400;
            font-style: italic;
            margin: 70px 0;
        }
        .item span {
            font-style: normal;
        }
        .panel {
            border: 1px solid #000000;
            border-radius:0 !important;
            transition: box-shadow 0.5s;
        }
        .panel:hover {
            box-shadow: 5px 0px 40px rgba(0,0,0, .2);
        }
        .panel-footer .btn:hover {
            border: 1px solid #000000;
            background-color: #fff !important;
            color: #000000;
        }
        .panel-footer h3 {
            font-size: 32px;
        }
        .panel-footer h4 {
            color: #aaa;
            font-size: 14px;
        }
        .panel-footer .btn {
            margin: 15px 0;
            background-color: #000000;
            color: #fff;
        }

        .panel .panel-heading {
            background-color:#eee;
            color:#666666;
            font-weight: bold;
            cursor: default;
        }
        .navbar {
            margin-bottom: 0;
            background-color: #000000;
            z-index: 9999;
            border: 0;
            font-size: 16px !important;
            line-height: 1.42857143 !important;
            letter-spacing: 3px;
            border-radius: 20px;
            font-family: font-family: Candara, Calibri, Segoe, 'Segoe UI', Optima, Arial, sans-serif;
        }
        .navbar li a, .navbar .navbar-brand {
            color: #fff !important;
        }
        .navbar-nav li a:hover, .navbar-nav li.active a {
            color: #000000 !important;
            background-color: #fff !important;
        }
        .navbar-default .navbar-toggle {
            border-color: transparent;
            color: #fff !important;
        }


        footer .glyphicon {
            font-size: 20px;
            margin-bottom: 20px;
            color: #000000;
        }
        @keyframes slide {
            0% {
                opacity: 0;
                transform: translateY(70%);
            }
            100% {
                opacity: 1;
                transform: translateY(0%);
            }
        }
        @-webkit-keyframes slide {
            0% {
                opacity: 0;
                -webkit-transform: translateY(70%);
            }
            100% {
                opacity: 1;
                -webkit-transform: translateY(0%);
            }
        }
    </style>
</head>
<body>
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand">EDUCATOR</a>
        </div>
        <ul class="nav navbar-nav">
            <li><a href="{% url 'ed4all:educator_home' %}">HOME</a></li>
            <li><a href="{% url 'ed4all:educator_incident_list' %}">INCIDENTS</a></li>
            <li class="active"><a href="{% url 'ed4all:educator_student_list' %}">STUDENTS</a></li>
            <!--<li><a href="{% url 'ed4all:incident_list' %}">SERVICES</a> </li> -->
            <li><a href="{% url 'index' %}">LOG OUT</a></li>
        </ul>
    </div>
</nav>

<div class="jumbotron text-center">
    <h1>Students</h1>
</div>

<div class="panel">
    <div class="container">
         <div class="text-center">
             <table class="table table-bordered table-hover sortable">
            <tbody>
             <tr class="panel-heading">
                <td>Student ID</td>
                <td>Student Name</td>
                 <td>Program</td>
                 <td>View/Report Incident</td>
            </tr>
    {% for s in student %}
             <tr>
                 <td>{{s.studentid}}</td>
                 <td>{{s.studentfname}} {{s.studentlname}}</td>
                 <td>{{s.program}}</td>
                 <td><a href="{% url 'ed4all:educator_student_view' s.studentid %}" data-original-title="View Detail" class="btn btn-primary btn-sm" type="button" >
                <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>
                View</a>
                     <a href="{% url 'ed4all:educator_create_incident' %}"
               data-original-title="report incident" class="btn btn-danger btn-sm" type="button" >
                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                Report Incident</a>
                 </td>
             </tr>
    {% endfor %}
            </tbody>
</div>
</body>
</html>

Student_Incident_Tracking_System/ed4all/templates/ed4all/incident_form.html
<!DOCTYPE html>
<html lang="en">

<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
</head>

<body>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand">Counselor</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="counselor_home.html">Home</a></li>
      <li><a href="student_list.html">Student List</a></li>
      <li><a href="incident_form.html">Incident List</a></li>
    </ul>
  </div>
</nav>
<h1>This is your Incident!</h1>
    <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" />
</form>
</body>
</html>