Student_Incident_Tracking_System/ed4all/urls.py
from django.conf.urls import url
from django.contrib import admin
from ed4all import views

urlpatterns = [
    url(r'^$', views.home, name="home"),

    # =========== student login ===========
    url(r'^student_home', views.student_home, name='student_home'),
    url(r'^student_view_detail', views.student_view_detail, name='student_view_detail'),
    url(r'^student_view_incident', views.student_view_incident, name='student_view_incident'),

    # =========== educator login ===========
    url(r'^educator_home', views.educator_home, name='educator_home'),
    url(r'^educator_create_incident', views.educator_create_incident, name='educator_create_incident'),
    url(r'^educator_student_list', views.educator_student_list, name='educator_student_list'),
    url(r'^educator_incident_list', views.educator_incident_list, name='educator_incident_list'),
    url(r'^educator_student_view/(?P<pk>[\w-]+)$', views.educator_student_view, name='educator_student_view'),

    # =========== counselor login ===========
    url(r'^counselor_home', views.counselor_home, name='counselor_home'),
    url(r'^student_list', views.student_list, name='student_list'),
    url(r'^student_view/(?P<pk>[\w-]+)$', views.student_view, name='student_view'),
    url(r'^incident_form', views.incident_create, name='incident_create'),
    url(r'^incident_list', views.incident_list, name='incident_list'),
    url(r'^incident_view/(?P<pk>[\w-]+)/$', views.incident_view, name='incident_view'),
    url(r'^incident_edit/(?P<pk>[\w-]+)/$', views.incident_edit, name='incident_edit'),
    url(r'^incident_delete/(?P<pk>[\w-]+)$', views.incident_delete, name='incident_delete'),

]

Student_Incident_Tracking_System/education4/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^ed4all/', include('ed4all.urls', namespace='ed4all')),

]

Student_Incident_Tracking_System/ed4all/views.py
from ed4all.models import Appointment, Counselor, Educator, Incident, Student, Studentprofile
from django.core.urlresolvers import reverse_lazy, reverse
from django.template import loader
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.forms import ModelForm
from django.views.decorators.csrf import csrf_exempt
from django import forms
from django.core.mail import send_mail


# ========== home =========

def home(request, template_name='ed4all/home.html'):
    incidents = Incident.objects.all()
    contents = {}
    contents["incidents"] = incidents
    return render(request, template_name, contents)


# ========== form =========

class IncidentForm(ModelForm):
    class Meta:
        model = Incident
        fields = ['incidentid', 'studentid', 'incidenttype', 'location', 'educatorid', 'counselorid', 'status']

class IncidentEditForm(ModelForm):
    class Meta:
        model = Incident
        fields = [ 'studentid', 'incidenttype', 'location', 'educatorid', 'counselorid', 'status']

class StudentForm(ModelForm):
    class Meta:
        model = Student
        fields = ['studentid', 'studentlname', 'studentfname', 'studentemailaddress', 'studentage', 'studentdob',
                  'street', 'city', 'zip', 'program', 'trackrepid', 'studentpassword', 'studenttype']


# =========== student login home ==========
@csrf_exempt
def student_home(request):
    err = True
    ctx = {}
    ctx["error"] = err
    if 'sid' in request.session:
        sid = request.session['sid']
        ctx["sid"] = sid
        student = Student.objects.get(studentid=sid)
        ctx['student'] = student
        return render(request, "ed4all/student_home.html", ctx)
    else:
        try:
            if request.method == 'POST':
                sid = request.POST['sid']
                pwd = request.POST['spwd']
                student = Student.objects.get(studentid=sid)
                if pwd == student.studentpassword:
                    ctx['sid'] = sid
                    ctx['student'] = student
                    request.session['sid'] = sid
                    request.session['spwd'] = pwd
                    return render(request, "ed4all/student_home.html", ctx)
                else:
                    err = False
                    ctx["error"] = err
                    ctx["message"] = "Wrong Password/Username"
                    return render(request, 'index.html', ctx)
            else:
                err = False
                ctx["error"] = err
                ctx["message"] = "Wrong Password/Username"
                return render(request, 'index.html', ctx)
        except Student.DoesNotExist:
            err = False
            ctx["error"] = err
            ctx["message"] = "Wrong Password/Username"
            return render(request, 'index.html', ctx)

# =========== faculty login home ==========
@csrf_exempt
def educator_home(request):
    err = True
    ctx = {}
    ctx["error"] = err
    if 'eid' in request.session:
        eid = request.session['eid']
        ctx["eid"] = eid
        educator = Educator.objects.get(educatorid=eid)
        ctx['educator'] = educator
        return render(request, "ed4all/educator_home.html", ctx)
    else:
        try:
            if request.method == 'POST':
                eid = request.POST['eid']
                pwd = request.POST['epwd']
                educator = Educator.objects.get(educatorid=eid)
                if pwd == educator.educatorpassword:
                    ctx['eid'] = eid
                    ctx['educator'] = educator
                    request.session['eid'] = eid
                    request.session['epwd'] = pwd
                    return render(request, "ed4all/educator_home.html", ctx)
                else:
                    err = False
                    ctx["error"] = err
                    ctx["message"] = "Wrong Password/Username"
                    return render(request, 'index.html', ctx)
            else:
                err = False
                ctx["error"] = err
                ctx["message"] = "Wrong Password/Username"
                return render(request, 'index.html', ctx)
        except Student.DoesNotExist:
            err = False
            ctx["error"] = err
            ctx["message"] = "Wrong Password/Username"
            return render(request, 'index.html', ctx)


# =========== counselor login home ==========
@csrf_exempt
def counselor_home(request):
    err = True
    ctx = {}
    ctx["error"] = err
    if 'cid' in request.session:
        cid = request.session['cid']
        ctx["cid"] = cid
        counselor = Counselor.objects.get(counselorid=cid)
        ctx['counselor'] = counselor
        return render(request, "ed4all/counselor_home.html", ctx)
    else:
        try:
            if request.method == 'POST':
                cid = request.POST['cid']
                pwd = request.POST['cpwd']
                counselor = Counselor.objects.get(counselorid=cid)
                if pwd == counselor.counselorpassword:
                    ctx['cid'] = cid
                    ctx['counselor'] = counselor
                    request.session['cid'] = cid
                    request.session['cpwd'] = pwd
                    return render(request, "ed4all/counselor_home.html", ctx)
                else:
                    err = False
                    ctx["error"] = err
                    ctx["message"] = "Wrong Password/Username"
                    return render(request, 'index.html', ctx)
            else:
                err = False
                ctx["error"] = err
                ctx["message"] = "Wrong Password/Username"
                return render(request, 'index.html', ctx)
        except Counselor.DoesNotExist:
            err = False
            ctx["error"] = err
            ctx["message"] = "Wrong Password/Username"
            return render(request, 'index.html', ctx)

# ========== Forms =========

#class IncidentForm(ModelForm):
#    class Meta:
#        model = Incident
#        fields = '__all__'

#class StudentForm(ModelForm):
#    class Meta:
#       model = Student
#        fields = '__all__'

class CounselorForm(ModelForm):
    class Meta:
        model = Counselor
        fields = '__all__'

class EducatorCreateForm(ModelForm):
    incidentid = forms.CharField(label='incidentid')
    educatorid = forms.ModelChoiceField(queryset=Educator.objects.all(), label='ID')
    studentid = forms.ModelChoiceField(queryset=Student.objects.all(), required=False, label='Student ID')
    counselorid = forms.ModelChoiceField(queryset=Counselor.objects.all(), required=False,
                                         label='Counselor')
    location = forms.CharField(label='Location')
    incidenttype = forms.CharField(label='Type')

    class Meta:
        model = Incident
        fields = ['incidentid','educatorid', 'studentid', 'counselorid', 'incidenttype', 'location', 'status']
        widgets = {
            'incidenttype': forms.TextInput,
            'location': forms.TextInput
        }

class StudentProfileForm(ModelForm):
        class Meta:
            model = Studentprofile
            fields = '__all__'

# =========== counselor view student profile and crud incident ==========

def student_list(request,template_name='ed4all/student_list.html'):
    student = Student.objects.all()
    ctx = {}
    ctx['student'] = student
    return render(request, template_name, ctx)

def student_view(request, pk, template_name='ed4all/student_view.html'):
    student= get_object_or_404(Student, studentid=pk)
    trackrep = get_object_or_404(Student,studentid=student.trackrepid)
    profile = Studentprofile.objects.filter(studentid=pk)
    ctx = {}
    ctx["student"] = student
    ctx["trackrep"] = trackrep
    ctx["profile"] = profile
    return render(request, template_name, ctx)

def incident_list(request,template_name='ed4all/incident_list.html'):
    ctx={}
    incident= Incident.objects.all()
    ctx['incident']=incident
    return render(request,template_name,ctx)

def incident_view(request, pk, template_name='ed4all/incident_view.html'):
    incident= get_object_or_404(Incident, incidentid=pk)
    student = Student.objects.filter(incident=pk)
    counselor=Counselor.objects.filter(incident=pk)
    ctx = {}
    ctx["i"] = incident
    ctx["s"] = student
    ctx['c']=counselor
    return render(request, template_name, ctx)

def incident_edit(request, pk, template_name='ed4all/incident_edit.html'):
    incident= get_object_or_404(Incident, incidentid=pk)
    form = IncidentEditForm(request.POST or None, instance=incident)
    if form.is_valid():
        form.save()
        return redirect('ed4all:incident_list')
    ctx = {}
    ctx["form"] = form
    ctx["incident"] = incident
    return render(request, template_name, ctx)

def incident_delete(request, pk, template_name='ed4all/incident_delete.html'):
    incident = get_object_or_404(Incident, incidentid=pk)
    if request.method=='POST':
        incident.delete()
        return redirect('ed4all:incident_list')
    ctx = {}
    ctx["incident"] = incident
    return render(request, template_name, ctx)

def incident_create(request, template_name='ed4all/incident_form.html'):
    form = IncidentForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('ed4all:counselor_home')
    ctx = {}
    ctx["form"] = form
    return render(request, template_name, ctx)

# =========== student view own profile ============
def student_view_detail(request, template_name='ed4all/student_view_detail.html'):
    pk = request.session['sid']
    student = get_object_or_404(Student, studentid=pk)
    trackrep = get_object_or_404(Student, studentid=student.trackrepid)
    profile = Studentprofile.objects.filter(studentid=pk)
    ctx = {}
    ctx["student"] = student
    ctx["trackrep"] = trackrep
    ctx["profile"] = profile
    return render(request, template_name, ctx)

Student_Incident_Tracking_System/ed4all/templates/index.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>login</title>
    {% load static %}
<link rel="stylesheet" href="{% static 'ed4all/login/css/login.css' %}" type="text/css" media="all" />
<script type="text/javascript" src="{% static 'ed4all/login/js/jQuery1.7.js' %}"></script>
<script type="text/javascript" src="{% static 'ed4all/login/js/jquery-1.8.2.min.js' %}"></script>
<script type="text/javascript" src="{% static 'ed4all/login/js/jquery1.42.min.js' %}"></script>
<script type="text/javascript" src="{% static 'ed4all/login/js/jquery.SuperSlide.js' %}"></script>
<script type="text/javascript" src="{% static 'ed4all/login/js/Validform_v5.3.2_min.js' %}"></script>
<script type="text/javascript">
$(document).ready(function(){
	var $tab_li = $('#tab ul li');
	$tab_li.hover(function(){
		$(this).addClass('selected').siblings().removeClass('selected');
		var index = $tab_li.index(this);
		$('div.tab_box > div').eq(index).show().siblings().hide();
	});
});
</script>

<script type="text/javascript">
$(function(){
	$(".screenbg ul li").each(function(){
		$(this).css("opacity","0");
	});
	$(".screenbg ul li:first").css("opacity","1");
	var index = 0;
	var t;
	var li = $(".screenbg ul li");
	var number = li.size();
	function change(index){
		li.css("visibility","visible");
		li.eq(index).siblings().animate({opacity:0},3000);
		li.eq(index).animate({opacity:1},3000);
	}
	function show(){
		index = index + 1;
		if(index<=number-1){
			change(index);
		}else{
			index = 0;
			change(index);
		}
	}
	t = setInterval(show,8000);
	//imgwidth
	var width = $(window).width();
	$(".screenbg ul img").css("width",width+"px");
});
</script>
</head>

<body>
<div id="tab">
  <ul class="tab_menu">
    <li class="selected">Student Login</li>
    <li>Educator Login</li>
    <li>Counselor Login</li>
  </ul>
  <div class="tab_box">

    <!-- studentlogin start -->
    <div>
      <div class="stu_error_box"></div>
      <form action="{% url 'ed4all:student_home' %}" method="post" class="stu_login_error">
          {% csrf_token %}
        <div id="sid">
          <label>StudentId：</label>
          <input type="text" id="stu_username_hide" name="sid" value="studentid" nullmsg="not null！" datatype="s6-18" errormsg="6~18！"/>
          <!--ajaxurl="demo/valid.jsp"-->
        </div>
        <div id="password">
          <label>Password：</label>
          <input type="password" id="stu_password_hide" name="spwd" value="studentpassword" nullmsg="not null" datatype="*6-16" errormsg="6-16！"/>
        </div>
        <div id="code">
          <label>Captcha：</label>
          <input type="text" id="stu_code_hide" name="code"  value="input" nullmsg="not null！" datatype="*4-4" errormsg="4 digit！"/>
          <img src="{% static 'ed4all/login/images/captcha.jpg' %}" title="change" alt="picture"/> </div>
        <div id="remember">
          <input type="checkbox" name="remember">
          <label>remember password</label>
        </div>
        <div id="login">
          <button type="submit">login</button>
        </div>

      </form>
    </div>
   <!-- -->
   <!-- faculty login-->
    <div class="hide">
     <div class="tea_error_box"></div>
      <form action="{% url 'ed4all:educator_home' %}" method="post" class="tea_login_error"> {% csrf_token %}
        <div id="eid">
          <label>EducatorId：</label>
          <input type="text" id="tea_username_hide" name="eid" value="educatorid" nullmsg="not null！" datatype="s6-18" errormsg="6~18digit！" sucmsg="passed！"/>
          <!--ajaxurl="demo/valid.jsp"--> 
        </div>
        <div id="epwd">
          <label>Password：</label>
          <input type="password" id="tea_password_hide" name="epwd" value="educatorpassword" nullmsg="notnull！" datatype="*6-16" errormsg="6~16！" sucmsg="pass！"/>
        </div>
        <div id="code">
          <label>Captcha：</label>
          <input type="text" id="tea_code_hide" name="code"  value="input" nullmsg="notnull！" datatype="*4-4" errormsg="4digit！" sucmsg="passed！"/>
          <img src="{% static 'ed4all/login/images/captcha.jpg' %}" title="change" alt="picture"/> </div>
        <div id="remember">
          <input type="checkbox" name="remember">
          <label>remember password</label>
        </div>
        <div id="login">
          <button type="submit">login</button>
        </div>
      </form>
    </div>
     <!-- -->
     <!-- counselor login -->
    <div class="hide">
    <div class="sec_error_box"></div>
      <form action="{% url 'ed4all:counselor_home' %}" method="post" class="sec_login_error">
          {% csrf_token %}
        <div id="cid">
          <label>CounselorId：</label>
          <input type="text" id="sec_username_hide" name="cid" value="counselorid" nullmsg="notnull" datatype="s6-18" errormsg="6-18digit！"/>
          <!--ajaxurl="demo/valid.jsp"--> 
        </div>
        <div id="cpwd">
          <label>Password：</label>
          <input type="password" id="sec_password_hide" name="cpwd" value="input" nullmsg="notnull" datatype="*6-16" errormsg="6-16digit！" />
        </div>
        <div id="code">
          <label>Captcha：</label>
          <input type="text" id="sec_code_hide" name="code"  value="input" nullmsg="notnull！" datatype="*4-4" errormsg="4digit！" />
          <img src="{% static 'ed4all/login/images/captcha.jpg' %}" title="change alt="picture/> </div>
        <div id="remember">
          <input type="checkbox" name="remember">
          <label>remember password</label>
        </div>
        <div id="login">
          <button type="submit">login</button>
        </div>
      </form>
    </div>
     <!-- -->
  </div>
</div>
<div class="bottom">©2017  <a href="javascript:;" target="_blank">Education4</a> <span></span><img width="13" height="16" src="{% static 'ed4all/login/images/copy_rignt_24.png' %}" /></div>
<div class="screenbg">
  <ul>
    <li><a href="javascript:;"><img src="{% static 'ed4all/login/images/0.png' %}"></a></li>
    <li><a href="javascript:;"><img src="{% static 'ed4all/login/images/1.jpg' %}"></a></li>
    <li><a href="javascript:;"><img src="{% static 'ed4all/login/images/2.jpg' %}"></a></li>
    <li><a href="javascript:;"><img src="{% static 'ed4all/login/images/3.jpg' %}"></a></li>
  </ul>

</div>
</body>
</html>